=== open-contracting/infrastructure/schema/project-level/project-package-schema.json
{
  "id": "https://standard.open-contracting.org/infrastructure/schema/0__9__3/project-package-schema.json",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Schema for an OC4IDS project package",
  "description": "A package of OC4IDS projects. Note that all projects within a package must have a unique project identifier.",
  "type": "object",
  "required": [
    "uri",
    "publisher",
    "publishedDate",
    "projects",
    "version"
  ],
  "properties": {
    "uri": {
      "title": "Package identifier",
      "description": "The URI of this package that identifies it uniquely in the world. Recommended practice is to use a dereferenceable URI, where a persistent copy of this package is available.",
      "type": "string",
      "format": "uri"
    },
    "publishedDate": {
      "title": "Published date",
      "description": "The date that this package was published. If this package is generated 'on demand', this date should reflect the date of the last change to the underlying contents of the package.",
      "type": "string",
      "format": "date-time"
    },
    "version": {
      "title": "OC4IDS schema version",
      "description": "The version of the OC4IDS schema used in this package, expressed as major.minor. For example: 0.9",
      "type": "string",
      "pattern": "^(\\d+\\.)(\\d+)$"
    },
    "projects": {
      "title": "Projects",
      "description": "A list of projects included in this package, in OC4IDS format.",
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "https://standard.open-contracting.org/infrastructure/schema/0__9__3/project-schema.json"
      },
      "uniqueItems": true
    },
    "publisher": {
      "title": "Publisher",
      "description": "Information to uniquely identify the publisher of this package.",
      "type": "object",
      "properties": {
        "name": {
          "title": "Name",
          "description": "The name of the organization or department responsible for publishing this data.",
          "type": "string",
          "minLength": 1
        },
        "scheme": {
          "title": "Scheme",
          "description": "The scheme that holds the unique identifiers used to identify the item being identified.",
          "type": [
            "string",
            "null"
          ]
        },
        "uid": {
          "title": "uid",
          "description": "The unique ID for this entity under the given ID scheme.",
          "type": [
            "string",
            "null"
          ]
        },
        "uri": {
          "title": "URI",
          "description": "A URI to identify the publisher.",
          "type": [
            "string",
            "null"
          ],
          "format": "uri"
        }
      },
      "required": [
        "name"
      ],
      "minProperties": 1
    },
    "license": {
      "title": "License",
      "description": "A link to the license that applies to the data in this package. A Public Domain Dedication or [Open Definition Conformant](https://opendefinition.org/licenses/) license is strongly recommended. The canonical URI of the license should be used. Documents linked from this file may be under other license conditions. ",
      "type": [
        "string",
        "null"
      ],
      "format": "uri"
    },
    "publicationPolicy": {
      "title": "Publication policy",
      "description": "A link to a document describing the publisher's [data user guide](https://standard.open-contracting.org/infrastructure/{{version}}/{{lang}}/guidance/data_user_guide/).",
      "type": [
        "string",
        "null"
      ],
      "format": "uri"
    }
  }
}

=== open-contracting/infrastructure/docs/examples/example.json
{
  "version": "0.9",
  "uri": "https://standard.open-contracting.org/infrastructure/0.9/en/_static/example.json",
  "publishedDate": "2018-12-10T15:53:00Z",
  "publisher": {
    "name": "Open Data Services Co-operative Limited",
    "scheme": "GB-COH",
    "uid": "9506232",
    "uri": "http://data.companieshouse.gov.uk/doc/company/09506232"
  },
  "license": "http://opendatacommons.org/licenses/pddl/1.0/",
  "publicationPolicy": "https://standard.open-contracting.org/1.1/en/implementation/publication_policy/",
  "projects": [
    {
      "id": "oc4ids-bu3kcz-m75-junctions-4-to-5-smart-motorway",
      "identifiers": [
        {
          "id": "M75/SM/4-5",
          "scheme": "internal"
        }
      ],
      "updated": "2018-12-10T15:53:00Z",
      "title": "M75 Junctions 4 to 5 upgrade smart motorway",
      "description": "Upgrading the 5km stretch of the M75 near Birmingham Airport, between junction 4 near Patcham and junction 5 at Windlesham, to an all-lane running smart motorway.",
      "status": "completed",
      "period": {
        "startDate": "2016-01-01T00:00:00Z",
        "endDate": "2018-12-10T00:00:00Z",
        "durationInDays": 1074
      },
      "sector": [
        "transport",
        "transport.road"
      ],
      "additionalClassifications": [
        {
          "scheme": "COFOG",
          "id": "04.5.1",
          "description": "Road transport (CS)"
        }
      ],
      "type": "expansion",
      "purpose": "To help support local economic growth and maintain mobility.",
      "relatedProjects": [
        {
          "id": "1",
          "scheme": "oc4ids",
          "identifier": "oc4ids-bu3kcz-m75-junctions-4-to-5-construction",
          "relationship": "construction",
          "title": "Original construction of M75 J4-5"
        }
      ],
      "assetLifetime": {
        "startDate": "2018-07-01T00:00:00Z",
        "endDate": "2040-07-01T00:00:00Z",
        "durationInDays": 8027
      },
      "locations": [
        {
          "id": "001",
          "description": "M75 J4 Patcham Interchange",
          "geometry": {
            "type": "Point",
            "coordinates": [
              52.2571843,
              -0.1163333
            ]
          },
          "gazetteer": {
            "scheme": "GEONAMES",
            "identifiers": [
              "2657507"
            ]
          },
          "address": {
            "streetAddress": "Patcham Interchange, New Road",
            "locality": "Patcham",
            "region": "Westshire",
            "postalCode": "WS20 5TV",
            "countryName": "United Kingdom"
          },
          "uri": "https://www.openstreetmap.org/node/202995"
        },
        {
          "id": "002",
          "description": "M75 J5 Windlesham interchange",
          "geometry": {
            "type": "Point",
            "coordinates": [
              52.1373584,
              -0.1198955
            ]
          },
          "gazetteer": {
            "scheme": "OSMN",
            "identifiers": [
              "https://www.openstreetmap.org/node/26571091"
            ]
          },
          "address": {
            "streetAddress": "Windlesham Interchange, Old Road",
            "locality": "Windlesham",
            "region": "Westshire",
            "postalCode": "WS21 6RZ",
            "countryName": "United Kingdom"
          },
          "uri": "https://www.openstreetmap.org/node/1638915385"
        }
      ],
      "budget": {
        "description": "Budget allocation for Motorways UK, aligned with the 2016-2018 strategic plan.",
        "amount": {
          "amount": 40000000,
          "currency": "GBP"
        },
        "requestDate": "2015-05-30T00:00:00Z",
        "approvalDate": "2015-06-24T00:00:00Z",
        "budgetBreakdown": [
          {
            "id": "2016",
            "description": "2016 budget allocation",
            "amount": {
              "amount": 10000000,
              "currency": "GBP"
            },
            "period": {
              "startDate": "2016-01-01T00:00:00Z",
              "endDate": "2016-12-31T00:00:00Z"
            },
            "sourceParty": {
              "name": "Motorways UK",
              "id": "GB-GOR-XX1234"
            }
          },
          {
            "id": "2017",
            "description": "2017 budget allocation",
            "amount": {
              "amount": 20000000,
              "currency": "GBP"
            },
            "period": {
              "startDate": "2017-01-01T00:00:00Z",
              "endDate": "2017-12-31T00:00:00Z"
            },
            "sourceParty": {
              "name": "Motorways UK",
              "id": "GB-GOR-XX1234"
            }
          },
          {
            "id": "2018",
            "description": "2018 budget allocation",
            "amount": {
              "amount": 10000000,
              "currency": "GBP"
            },
            "period": {
              "startDate": "2018-01-01T00:00:00Z",
              "endDate": "2018-12-31T00:00:00Z"
            },
            "sourceParty": {
              "name": "Motorways UK",
              "id": "GB-GOR-XX1234"
            }
          }
        ]
      },
      "parties": [
        {
          "name": "Motorways UK",
          "id": "GB-GOR-XX1234",
          "identifier": {
            "scheme": "GB-GOR",
            "legalName": "Motorways UK",
            "id": "XX1234",
            "uri": "https://government-organisation.register.gov.uk/records/XX1234"
          },
          "additionalIdentifiers": [
            {
              "scheme": "GB-GOV",
              "legalName": "Motorways UK",
              "id": "ABCDE"
            }
          ],
          "address": {
            "postalCode": "LL55 4NY",
            "countryName": "United Kingdom",
            "streetAddress": "8 Mountain Walk",
            "region": "Westshire",
            "locality": "Patcham"
          },
          "contactPoint": {
            "name": "Motorways Manager",
            "email": "EX12345@motorwaysuk.gov.uk",
            "telephone": "+44 0123 456 7890",
            "faxNumber": "+44 0123 456 7891"
          },
          "roles": [
            "procuringEntity",
            "buyer",
            "publicAuthority",
            "funder",
            "payee"
          ],
          "people": [
            {
              "id": "1",
              "name": "Jane Bloggs",
              "jobTitle": "Chair"
            }
          ]
        },
        {
          "name": "A1 Expert Smart Moto Design",
          "id": "GB-COH-11111111",
          "identifier": {
            "scheme": "GB-COH",
            "id": "11111111",
            "legalName": "A1 Expert Smart Moto Design Ltd",
            "uri": "https://beta.companieshouse.gov.uk/company/11111111"
          },
          "address": {
            "streetAddress": "Farm Grove, Prince Road",
            "locality": "Patcham",
            "region": "Westshire",
            "postalCode": "WS18 5BW",
            "countryName": "United Kingdom"
          },
          "contactPoint": {
            "name": "Kim Designer",
            "email": "kim.designerd@a1expertsmart.com",
            "telephone": "+44 0123 456 7890",
            "url": "https://www.example.com"
          },
          "roles": [
            "supplier",
            "tenderer"
          ]
        },
        {
          "name": "Motorway Design Services PLC",
          "id": "GB-COH-12345678",
          "identifier": {
            "scheme": "GB-COH",
            "id": "12345678",
            "legalName": "Motorway Design Services PLC",
            "uri": "https://beta.companieshouse.gov.uk/company/22222222"
          },
          "address": {
            "streetAddress": "567 High Street",
            "locality": "Mareham",
            "region": "Eastshire",
            "postalCode": "ES22 3TW",
            "countryName": "United Kingdom"
          },
          "roles": [
            "tenderer"
          ]
        },
        {
          "name": "Expert Motorway Supervisors Ltd",
          "id": "GB-COH-22222222",
          "identifier": {
            "scheme": "GB-COH",
            "id": "22222222",
            "legalName": "Expert Motorway Supervisors Ltd",
            "uri": "https://beta.companieshouse.gov.uk/company/22222222"
          },
          "address": {
            "streetAddress": "9 Seaview Road",
            "locality": "London",
            "region": "London",
            "postalCode": "SE1 1EZ",
            "countryName": "United Kingdom"
          },
          "contactPoint": {
            "name": "Supervisor Manager",
            "email": "supervisor.manager@example.com",
            "telephone": "+44 0123 456 7890",
            "faxNumber": "+44 0123 456 7891",
            "url": "https://www.example.com"
          },
          "roles": [
            "supplier",
            "tenderer"
          ]
        },
        {
          "name": "Concrete Motorways Construction",
          "id": "GB-COH-33333333",
          "identifier": {
            "scheme": "GB-COH",
            "id": "33333333",
            "legalName": "Concrete Motorways Construction Ltd",
            "uri": "https://beta.companieshouse.gov.uk/company/33333333"
          },
          "address": {
            "streetAddress": "5 Example Grove",
            "locality": "London",
            "region": "London",
            "postalCode": "SW1A 1AA",
            "countryName": "United Kingdom"
          },
          "contactPoint": {
            "name": "Construction Manager",
            "email": "construction.example@example.com",
            "telephone": "+44 0123 456 7890",
            "faxNumber": "+44 0123 456 7891",
            "url": "https://www.example.com"
          },
          "roles": [
            "supplier",
            "tenderer"
          ],
          "beneficialOwners": [
            {
              "id": "1",
              "name": "Juan Perez",
